### ISSUE TITLE
NetLogo Web: import-a:pcolors fails if png image not rgba

### ISSUE THREAD

**Issue by gabriel-wurzer** [NetLogo/ImportA-Extension#1] opened 2022-04-26 09:50 UTC
A png dataurl must be rgba for import-a:pcolors to succeed. In all other cases NetLogo reports "ERROR: Failed to construct 'ImageData': The input data length is not a multiple of 4." (tested on Chrome 100.0.4896.127 64-Bit on Windows; and Firefox 99.0.1 64-Bit which gives the rather more cryptic "ERROR: An attempt was made to use an object that is not, or is no longer, usable")

Steps to reproduce:

1. extract attached [files.zip](https://github.com/NetLogo/ImportA-Extension/files/8561796/files.zip) and open import-a-rgb-rgba.html in a browser
2. open (enlarge) the command center
3. open the developer console (in Chrome: choose Menu > More Tools.. > Developer Tools and switch to the Console tab)
4. press the button and choose the file rgb.bin (which contains a base64-encoded RGB png)
5. see the exception in the Console:

`Uncaught DOMException: Failed to construct 'ImageData': The input data length is not a multiple of 4.
    at window.synchroDecoder (file:///C:/temp/mdab2/preprocessing/import-a-rgb-rgba.html:25286:102375)
    at file:///C:/temp/mdab2/preprocessing/import-a-rgb-rgba.html:62275:34
    at Object.importPColors [as PCOLORS] (file:///C:/temp/mdab2/preprocessing/import-a-rgb-rgba.html:66040:59)
    at eval (eval at <anonymous> (file:///C:/temp/mdab2/preprocessing/import-a-rgb-rgba.html:79:38), <anonymous>:8:44)
    at FileReader.reader.onload (file:///C:/temp/mdab2/preprocessing/import-a-rgb-rgba.html:79867:18)`

6. also observe that the output shown in the command center remains empty
7. now press the button again and choose rgba.bin (which contains a base64-encoded RGBA png)
8. observe that "OK" is now shown in the command center (and no exception is printed to the console)

Suggestions / possible solutions:

- Quick Fix: the documentation at https://github.com/NetLogo/ImportA-Extension/blob/hexy/README.md and https://ccl.northwestern.edu/netlogo/docs/dictionary.html#import-pcolors should be updated saying that import-a requires  a base64 png which must be RGBA at the moment.
- In the long run ideally all PNGs should be supported [Grayscale, RGB, RGBA, Indexed, .... I have never experienced a problem with NetLogo Desktop when loading them]

Other notes:

- I am unsure if JPGs also have any "implied" color semantics in NetLogo Web; 
- I also attach the python code that generates the rgba.bin and rgb.bin file, because I found out that online png to dataurl converters generate only RGB
 
[generate_rgb_rgba_1pix_png.py.zip](https://github.com/NetLogo/ImportA-Extension/files/8561939/generate_rgb_rgba_1pix_png.py.zip)

**Comment by gabriel-wurzer** [comment] 2022-04-26 16:21
P.S.: forgot program versions,

NetLogo 6.2.0 (December 22, 2020) and thus probably: Netlogo Web as of October 15th, 2020 - v2.8.1
Extension API version: 6.1
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.12

**Comment by TheBizzle** [comment] 2022-04-27 16:19
Thanks for the very detailed and informative report! :sunglasses:

This seems to be a duplicate of https://github.com/NetLogo/SynchroDecoder/issues/3, which was fixed a couple of weeks ago, but hasn't been deployed to netlogoweb.org yet, so I'll be closing this as a duplicate.

**Closed as completed by TheBizzle** 2022-04-27 16:19 UTC
Labels: duplicate

**Comment by gabriel-wurzer** [comment] 2022-04-27 17:07
Thanks 👍 great to hear that! Gabriel-- sent from my cell phone --Am 27.04.2022 18:20 schrieb Jason Bertsche ***@***.***>:
Closed #1.
